### ISSUE TITLE
Analysis report 

### ISSUE THREAD

**Issue by Albocoder** [Albocoder/CS319-Group22#1]
Everyone must contribute to the Analysis Design as described in the "DIVIDED WORK" document <a href="https://docs.google.com/document/d/1ksyxY5n6eS7RMty6McKC3e1JEaIlfD1reLcFvvTAIhc/edit?usp=sharing">here</a>. I will try to provide any figure if possible, help Ertugrul with overview and format the document, since I finished my part.

**Comment by ugurdogrusoz** [comment]
Hi Guys, as I tried to explain in class today, I strongly recommend that you get together and do especially Analysis and Design phases together. There will of course be things that can be done independently after discussion but you should agree on things first.

**Comment by Albocoder** [comment]
Hi Prof. @ugurdogrusoz I want to say that we me on Tuesday as you can see from our wiki page. The purpose of that meeting was exactly that. We collaborated on deciding all the use cases and wrote them in a <a href="https://docs.google.com/document/d/1RTADikhdRUm-ktyqlXkrG9VyKBvXYNaStVaFdhiYCnc/edit?usp=sharing">document</a>, we also make the UML diagram as seen <a href="https://drive.google.com/open?id=0BwarO5T4uRH5Ym5RQl9PYUlSaWc">here</a>. Then we divided the rest of the work <a href="https://docs.google.com/document/d/1ksyxY5n6eS7RMty6McKC3e1JEaIlfD1reLcFvvTAIhc/edit?usp=sharing">like this</a>. Keeping this last document in mind we decided not to meet in order for us to have time to finally do our separate parts.

**Comment by Albocoder** [comment]
@aligunes195 @cevatbarisyilmaz @Kaxell 
Guys I finished formatting the document to be suitable to google docs. I left the blank spaces for you to enter what you have been working for. Please make sure you enter everything you were assigned before midnight of Friday.

**Comment by Albocoder** [comment]
@aligunes195 last call. Please copy what you did to the free place in the main document in drive

**Comment by Kaxell** [comment]
Hey, I made a last check and add some small explanations, uploaded a pdf version as final.

**Comment by Albocoder** [comment]
Milestone was reached but the issue was closed after!
Congratulations!!!
