### ISSUE TITLE
Upload your reports to Github

### ISSUE THREAD

**Issue by ugurdogrusoz** [Albocoder/CS319-Group22#2]
As opposed to having links to an external document (i.e. Google doc in your case). We'd like to verify that you submitted your reports by the due date this way. PDF is fine.
Please do so and let me know.
PS. This doesn't mean you can't collaboratively create your documents through Google docs. Just convert to pdf and upload before each deadline.

**Comment by Albocoder** [comment]
@ugurdogrusoz 
We actually "submitted" on due date. It can be verified on the top of the document where it says last edit. But do we get any penalty for not uploading it in the hub, since it was our first time?

**Comment by Kaxell** [comment]
Hello sir, I uploaded the pdf version, but since it my first time I wasn't sure about where to upload. But I can prove it is uploaded before the deadline, which can be verified with this [link](http://i.hizliresim.com/1Nl9ab.png). I am sorry for my mistake.  
Ertuğrul Akay

**Comment by ugurdogrusoz** [comment]
I don't see "last edit time stamp" (probably since I don't have edit access) but I trust you guys it was on time. Thanks for uploading it to Github. Please continue to do so in upcoming deadlines.
