### ISSUE TITLE
Problem with the InGame UI

### ISSUE THREAD

**Issue by Albocoder** [Albocoder/CS319-Group22#7]
In this issue I am describing some minor problems I found in the InGame UI. 
Firstly I would like to congratulate you for this cool looking UI. 

The issues are:
1) The Chat panel seems to only be responsive when enlarging but when the user wants to shrink it the area doesn't shrink but cuts out the components.
2) The InGameView class is supposed to extend from JFrame since it will be a frame not a panel for a frame as we discussed in a group meeting.
3) No Class other than the ViewManager class is allowed to have a main. At the moment ViewManager doesn't have a main because most of its function don't work due to lack of other classes. (But you are free to write a main there only for testing purposes)
4) The bad language used in the view is highly discouraged.(In later versions of the game we might even punish players for doing that)

**Comment by aligunes195** [comment]
The issues:

1. Yeah, I know that there are bugs in the view, even more than you said, but it is only the first version and I will solve the bugs when Lobby and some other classes will be implemented. You know that we are not allowed to use external libraries and it makes this view really hard to implement some parts, especially typing message part. It is the most buggy part actually, I'm aware. Thanks for the warning.
2. Ok, it should be a frame then.
3. The main method, actually, for only trial but I forgot to make it comment lines. 
4. The messages that I wrote is just for the trial too. Come on, it is just a joke :) Of course I will delete these.

**Comment by aligunes195** [comment]
Addition:
1. The colors of panels or images, and some other components like buttons can be changed. 
2. Fonts or colors of texts can be changed too. 
When we have an entirely working code, we can decide as group what to about these little things.

**Comment by Albocoder** [comment]
> I will solve the bugs when Lobby and some other classes will be implemented.
Those view bugs can be solved without the need of having Lobby and other classes. I suggest you work on solving those problems so that we can focus on integrating the classes on Sunday when all are supposed to be done. Integration will cause some other bugs and view is the last thing we want to deal with at that stage. So plz make sure you got no bugs on your classes. Meanwhile I will integrate LoginView with the AccessHandles and AccessConnection
